routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('mainpages.home');
// });


Route::get('/', 'MainController@index');

Route::get('/products/category/{url_name}', 'MainController@products_category');
Route::get('/products/subcategory/{url_name}', 'MainController@products_subcategory');

Route::get('/products/special-products', 'MainController@specialproduct');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin', 'Admin\Auth\AdminLoginController@showAdminLogin')->name('admin.login');
Route::post('/admin', 'Admin\Auth\AdminLoginController@Login');


Route::get('/admin/home', 'Admin\Auth\AdminController@index');
Route::get('/admin/user_list', 'Admin\Auth\AdminController@userList');
Route::get('/admin/register', 'Admin\Auth\AdminController@register');
Route::post('/admin/register', 'Admin\Auth\AdminController@registerUser');
Route::get('/admin/user/{id}/edit', 'Admin\Auth\AdminController@editUser');
Route::patch('/admin/user/{id}', 'Admin\Auth\AdminController@updateUser');
Route::get('/admin/user/changepassword', 'Admin\Auth\AdminController@changeUserPassword');
Route::patch('/admin/changepassword/{id}', 'Admin\Auth\AdminController@updatePassword');


Route::get('/admin/getSubCategory', 'Admin\ProductController@getSubCategory');

Route::resource('/admin/category', 'Admin\CategoryController');
Route::resource('/admin/subcategory', 'Admin\SubCategoryController');
Route::resource('/admin/product', 'Admin\ProductController');
Route::resource('/admin/specialproduct', 'Admin\SpecialController');

app/Special.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;


class Special extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'specials';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['title', 'url_name', 'images', 'unites', 'price', 'productId', 'status', 'sl_date', 'content'];

    
}

app/Http/Controllers/Admin/SpecialController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Special;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\ServiceProvider;
use File;
use Image;
use Session;
use Redirect,Response;
use Auth;

class SpecialController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }


    public function index()
    {
        $myproducts = Special::all();
        return view('admin.pages.special.index', compact('myproducts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.special.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $request->validate([
                'title' => ['required', 'string', 'max:255'],
                'url_name' =>['required', 'string', 'regex:/^([-a-z0-9_ ])+$/i', 'unique:specials', 'alpha_dash', 'max:255'],
                'status'=>['required','string'],
                'unites'=>['required','string'],
                'productId'=>['required'],
                'sl_date'=>['required'],
                'price'=>['required'],
                'content'=>['string'],
                'images'=>['required'],
                ]);

        $file = $request->file('images');

        // dd($file);

        if (!empty($file)){

            $image = Image::make($file);

            $path = 'uploads/products/';

            $fileName = $request->file('images')->getClientOriginalName();
            $extension = explode(".", strtolower($fileName));
            $filetype = end($extension);
            $filenewname = rand(1000000, 999999999).time().".".$filetype;
          
            $image->save($path.$filenewname);
            
            $image->resize(400, 400);
            $image->save($path.$filenewname);
               
            $myproduct = new Special();

            $myproduct->title = $request->title;
            $myproduct->url_name = $request->url_name;
            $myproduct->sl_date = $request->sl_date;
            $myproduct->unites = $request->unites;
            $myproduct->productId = $request->productId;
            $myproduct->price = $request->price;
            $myproduct->status = $request->status;
            $myproduct->content = $request->content;
            $myproduct->images = $filenewname;

            $myproduct->save();

        }else{
            $requestData = $request->all();
            Special::create($requestData);
        }

        return Redirect::to("/admin/specialproduct")->withSuccess('Great! Product Add successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Special  $special
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $myproduct=Special::findOrFail($id);
        return view('admin.pages.special.show', compact('myproduct'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Special  $special
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $myproduct=Special::findOrFail($id);
        return view('admin.pages.special.edit', compact('myproduct'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Special  $special
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request);
        $request->validate([
                'title' => ['required', 'string', 'max:255'],
                'url_name' =>['required', 'string', 'regex:/^([-a-z0-9_ ])+$/i', 'alpha_dash', 'max:255'],
                'status'=>['required','string'],
                'unites'=>['required','string'],
                'productId'=>['required'],
                'price'=>['required'],
                'content'=>['string'],
                ]);

            $file = $request->file('images');

          

            if (!empty($file)){
            
            $sproduct = Special::find($id);
           
            $pathToImage = 'uploads/products/'.$sproduct['images'];

            $image = Image::make($file);

            $path = 'uploads/products/';

            $fileName = $request->file('images')->getClientOriginalName();
            $extension = explode(".", strtolower($fileName));
            $filetype = end($extension);
            $filenewname = rand(1000000, 999999999).time().".".$filetype;
            
            //$image->save($path.$filenewname);
            
            $image->resize(400, 400);
            $image->save($path.$filenewname);

            if($image->save()==true){
                File::delete($pathToImage);
            }

            $sproduct->title = $request->title;
            $sproduct->url_name = $request->url_name;
            $sproduct->sl_date = $request->sl_date;
            $sproduct->unites = $request->unites;
            $sproduct->productId = $request->productId;
            $sproduct->price = $request->price;
            $sproduct->status = $request->status;
            $sproduct->content = $request->content;
            $sproduct->images = $filenewname;
            $sproduct->update();

        }else{
            $mycategory = Special::findOrFail($id);
            $mycategory->update($request->all());
        }

        return Redirect::to("/admin/specialproduct")->withSuccess('Great! Product info updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Special  $special
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $mypoem = Special::find($id);

        if($mypoem['images']){
            $pathToImage = 'uploads/products/'.$mypoem['images'];

            File::delete($pathToImage);
        }
        $mypoem->delete();
        
        return redirect('/admin/specialproduct')->with('success', 'Product deleted!');
    }
}

resources/views/admin/pages/special/create.blade.php
@extends('admin.layouts.mainlayout')

@section('content')
        
    <div class="container-fluid">
        <h3 class="my-4">Add New Special Item</h3>
        <hr>
        
            {{-- <li class="breadcrumb-item active">Dashboard</li> --}}
            @if ($message = Session::get('success'))
	           <div class="alert alert-success alert-block">
	              <button type="button" class="close" data-dismiss="alert">×</button>
	              <strong>{{ $message }}</strong>
	           </div>
	           <br>
	        @endif
		
        <div class="row">
        	<div class="col-md-6">    
        		<form action="{{ route('specialproduct.store') }}" method="post" enctype="multipart/form-data">
        		@csrf    
                
                    	
        		<div class="form-group">
        		    <label for="">Special Product Name</label>
        		    <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" placeholder="Special Product Name" autofocus autocomplete="title" required> 
        		    @error('title')
        		        <span class="invalid-feedback" role="alert">
        		            <strong>{{ $message }}</strong>
        		        </span>
        		    @enderror
        		</div>
                <div class="form-group">
                    <label for="">Special Product Id</label>
                    <input type="text" class="form-control @error('productId') is-invalid @enderror" name="productId" value="{{ old('productId') }}" placeholder="Product Id" autofocus autocomplete="productId" required> 
                    @error('productId')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
        		<div class="form-group">
                    <label for="">Special Product Url Name</label> <small>(This name is unique and No special Characters or space)</small>
                    <input type="text" class="form-control @error('url_name') is-invalid @enderror" name="url_name" value="{{ old('url_name') }}" placeholder="Url Name" autofocus autocomplete="url_name" required> 
                    @error('url_name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Serial Date</label>
                    <input type="date" class="form-control @error('sl_date') is-invalid @enderror" name="sl_date" value="{{ old('sl_date') }}" autofocus autocomplete="sl_date" required> 
                    @error('sl_date')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="content">Content</label>
                    <textarea class="form-control" name="content" id="content" rows="4"></textarea>
                    @error('content')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>  
        	</div>
        	<div class="col-md-6">
	    		<div class="form-group">
	    		    <label for="">Status</label>
	    		    <select class="form-control @error('status') is-invalid @enderror" name="status" required="required">
	    		      <option value="" active>Select a option</option>
	    		      <option>Active</option>
	    		      <option>Inactive</option>
                      <option>Out of Stock</option>
	    		    </select>
	    		    @error('type')
	    		        <span class="invalid-feedback" role="alert">
	    		            <strong>{{ $message }}</strong>
	    		        </span>
	    		    @enderror
	    		</div>
                <div class="form-group">
                    <label for="">Units</label> 
                    <input type="text" class="form-control @error('unites') is-invalid @enderror" name="unites" value="{{ old('unites') }}" placeholder="Product Unit" autofocus autocomplete="unites" required> 
                    @error('unites')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Unit Price</label> 
                    <input type="text" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ old('price') }}" placeholder="Unit Price" autofocus autocomplete="price" required> 
                    @error('price')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="files">Product Image</label>
                    <input type="file" class="form-control-file @error('images') is-invalid @enderror" name="images" required="required" id="files">
                    <small>Icon size 400x400 px</small>
                    @error('images')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Selected Image</label><br>
                    <img style="max-height: 150px;" class="img-responsive" id="image" />
                </div>
        	</div>
        </div>
        <div class="row">
        	<div class="col-md-6">
        		<button type="submit" class="btn btn-primary mb-2">Save</button>
        		<button type="reset" class="btn btn-primary mb-2">Reset</button>
        	</div>
        </div>
        </form>
    </div>                

@endsection

@section('javascript')


<script type="text/javascript">
     document.getElementById("files").onchange = function () {
        var reader = new FileReader();

        reader.onload = function (e) {
            // get loaded data and render thumbnail.
            document.getElementById("image").src = e.target.result;
        };

        // read the image file as a data URL.
        reader.readAsDataURL(this.files[0]);
    };
</script>

@endsection

resources/views/admin/pages/special/edit.blade.php
@extends('admin.layouts.mainlayout')

@section('content')
        
    <div class="container-fluid">
        <h3 class="my-4">Edit Special Item</h3>
        <hr>
        
            {{-- <li class="breadcrumb-item active">Dashboard</li> --}}
            @if ($message = Session::get('success'))
               <div class="alert alert-success alert-block">
                  <button type="button" class="close" data-dismiss="alert">×</button>
                  <strong>{{ $message }}</strong>
               </div>
               <br>
            @endif
        
        <div class="row">
            <div class="col-md-6">    
                <form action="{{ route('specialproduct.update', $myproduct->id) }}" method="post" enctype="multipart/form-data">
                @csrf
                @method('PUT') 
                        
                <div class="form-group">
                    <label for="">Special Product Name</label>
                    <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $myproduct->title }}"  autofocus autocomplete="title" required> 
                    @error('title')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Special Product Id</label>
                    <input type="text" class="form-control @error('productId') is-invalid @enderror" name="productId" value="{{ $myproduct->productId }}" autofocus autocomplete="productId" required> 
                    @error('productId')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Special Product Url Name</label> <small>(This name is unique and No special Characters or space)</small>
                    <input type="text" class="form-control @error('url_name') is-invalid @enderror" name="url_name" value="{{ $myproduct->url_name }}" placeholder="Url Name" autofocus autocomplete="url_name" required> 
                    @error('url_name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Serial Date</label>
                    <input type="date" class="form-control @error('sl_date') is-invalid @enderror" name="sl_date" value="{{ $myproduct->sl_date }}" autofocus autocomplete="sl_date" required> 
                    @error('sl_date')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="content">Content</label>
                    <textarea class="form-control" name="content" id="content" rows="4">{{ $myproduct->content }}</textarea>
                    @error('content')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>  
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="">Status</label>
                    <select class="form-control @error('status') is-invalid @enderror" name="status" required="required">
                        <option value="" active>Select a option</option>
                        <option {{ $myproduct->status == 'Active' ? 'selected' : '' }}>Active</option>
                        <option {{ $myproduct->status == 'Inactive' ? 'selected' : '' }}>Inactive</option>
                        <option {{ $myproduct->status == 'Out of Stock' ? 'selected' : '' }}>Out of Stock</option>
                    </select>
                    @error('type')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Units</label> 
                    <input type="text" class="form-control @error('unites') is-invalid @enderror" name="unites" value="{{ $myproduct->unites }}"  autofocus autocomplete="unites" required> 
                    @error('unites')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="">Unit Price</label> 
                    <input type="text" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ $myproduct->price }}" autofocus autocomplete="price" required> 
                    @error('price')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="files">Product Image</label>
                    <input type="file" class="form-control-file @error('images') is-invalid @enderror" name="images" id="files">
                    <small>Icon size 400x400 px</small>
                    @error('images')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="form-group">
                    <label>Selected Image</label><br>
                    <img style="max-height: 150px;" src="{{ asset('uploads/products/'.$myproduct->images) }}" class="img-responsive" id="image" />
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <button type="submit" class="btn btn-primary mb-2">Update</button>
            </div>
        </div>
        </form>
    </div>                

@endsection

@section('javascript')


<script type="text/javascript">
     document.getElementById("files").onchange = function () {
        var reader = new FileReader();

        reader.onload = function (e) {
            // get loaded data and render thumbnail.
            document.getElementById("image").src = e.target.result;
        };

        // read the image file as a data URL.
        reader.readAsDataURL(this.files[0]);
    };
</script>

@endsection

resources/views/admin/pages/special/index.blade.php
@extends('admin.layouts.mainlayout')

@section('content')
        
    <div class="container-fluid">

        <h3 class="my-4" style="text-decoration: underline;">Special Products List</h3>
        
            @if ($message = Session::get('success'))
            <hr>
               <div class="alert alert-success alert-block">
                  <button type="button" class="close" data-dismiss="alert">×</button>
                  <strong>{{ $message }}</strong>
               </div>
               <br>
            <hr>
            @endif
        
        

        <div class="card mb-4">
            <div class="card-header">
              <a class="btn btn-sm btn-primary" href="{{ route('specialproduct.create') }}">Add New</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                              <th scope="col">Sl No</th>
                              <th scope="col">Product Name</th>
                              <th scope="col">Url Name</th>                              
                              <th scope="col">Unit</th>
                              <th scope="col">Price</th>
                              <th scope="col">Status</th>
                              <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                              <th scope="col">Sl No</th>
                              
                              <th scope="col">Product Name</th>
                              <th scope="col">Url Name</th>                              
                              <th scope="col">Unit</th>
                              <th scope="col">Price</th>
                              <th scope="col">Status</th>
                              <th scope="col">Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach($myproducts as $item)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $item->title }}</td>
                                    <td>{{ $item->url_name }}</td>
                                    <td>{{ $item->unites }}</td>
                                    <td>{{ $item->price }}</td>
                                    
                                    <td {{ $item->status=='Inactive' ? 'style=color:red' : ''}}>{{ $item->status }}</td>
                                    <td>
                                      <a class="btn btn-sm btn-info" href="{{ route('specialproduct.show', $item->id) }}"><i class="fas fa-location-arrow"></i></a>
                                        <a class="btn btn-sm btn-primary" href="{{ route('specialproduct.edit', $item->id) }}"><i class="fas fa-edit"></i></a> 
                                        
                                        <form action="{{ route('specialproduct.destroy', $item->id)}}" method="post">
                                          @csrf
                                          @method('DELETE')
                                          <button class="btn btn-sm btn-danger" type="submit">
                                            <i class="fas fa-trash-alt"></i></button>
                                        </form>                                     
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        
    </div>                

@endsection

resources/views/admin/pages/special/show.blade.php
@extends('admin.layouts.mainlayout')

@section('content')
        
    <div class="container-fluid">

        <h3 class="my-4" style="text-decoration: underline;">Spacial Product Details</h3>
        
            @if ($message = Session::get('success'))
            <hr>
               <div class="alert alert-success alert-block">
                  <button type="button" class="close" data-dismiss="alert">×</button>
                  <strong>{{ $message }}</strong>
               </div>
               <br>
            <hr>
            @endif
        
        

        <div class="card mb-4">
            <div class="card-header">
            	<a class="btn btn-sm btn-primary" href="{{ route('specialproduct.index') }}">Back</a>
              <a class="btn btn-sm btn-info" href="{{ route('specialproduct.edit', $myproduct->id) }}">Edit</a>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover" id="" width="100%" cellspacing="0">
                        
                        <tr>
                        	<th>Special Product Name</th>
                        	<td>{{ $myproduct->title }}</td>
                        </tr>
                        <tr>
                            <th>Special Product ID</th>
                            <td>{{ $myproduct->productId }}</td>
                        </tr>
                        <tr>
                        	<th>Url Name</th>
                        	<td>{{ $myproduct->url_name }}</td>
                        </tr>
                        <tr>
                            <th>Sl Date</th>
                            <td>{{ $myproduct->sl_date }}</td>
                        </tr>
                        <tr>
                        	<th>Product Unit</th>
                        	<td>{{ $myproduct->unites }}</td>
                        </tr>
                        <tr>
                        	<th>Prodoct Price</th>
                        	<td>{{ $myproduct->price }} (BDT)</td>
                        </tr>
                        <tr>
                        	<th>Prodoct Status</th>
                        	<td>{{ $myproduct->status }}</td>
                        </tr>
                        <tr>
                        	<th>Prodoct Image</th>
                        	<td>
								<img style="max-height: 100px" src="{{ asset('uploads/products/'.$myproduct->images) }}">
                        	</td>
                        </tr>
                        <tr>
                        	<th>Prodoct Description</th>
                        	<td>{{ $myproduct->content }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div> 
               

@endsection