routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('mainpages.home');
// });


Route::get('/', 'MainController@index');

Route::get('/products/category/{url_name}', 'MainController@products_category');
Route::get('/products/subcategory/{url_name}', 'MainController@products_subcategory');

Route::get('/products/special-products', 'MainController@specialproduct');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/admin', 'Admin\Auth\AdminLoginController@showAdminLogin')->name('admin.login');
Route::post('/admin', 'Admin\Auth\AdminLoginController@Login');


Route::get('/admin/home', 'Admin\Auth\AdminController@index');
Route::get('/admin/user_list', 'Admin\Auth\AdminController@userList');
Route::get('/admin/register', 'Admin\Auth\AdminController@register');
Route::post('/admin/register', 'Admin\Auth\AdminController@registerUser');
Route::get('/admin/user/{id}/edit', 'Admin\Auth\AdminController@editUser');
Route::patch('/admin/user/{id}', 'Admin\Auth\AdminController@updateUser');
Route::get('/admin/user/changepassword', 'Admin\Auth\AdminController@changeUserPassword');
Route::patch('/admin/changepassword/{id}', 'Admin\Auth\AdminController@updatePassword');


Route::get('/admin/getSubCategory', 'Admin\ProductController@getSubCategory');

Route::resource('/admin/category', 'Admin\CategoryController');
Route::resource('/admin/subcategory', 'Admin\SubCategoryController');
Route::resource('/admin/product', 'Admin\ProductController');
Route::resource('/admin/specialproduct', 'Admin\SpecialController');

resources/views/admin/partials/mainfooter.blade.php
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="text-muted">Copyright &copy; www.krishanbari.xyz 2020</div>
            
            </div>
            <div class="col-md-6">
                <p class="text-right">Developed by:
                &middot;
                <a href="#">Md KHalid Hossain</a></p>
            </div>
        </div>
        {{-- <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; www.krishanbari.xyz 2020</div>
            <div>
                Developed by:
                &middot;
                <a href="#">Md KHalid Hossain</a>
            </div>
        </div> --}}
    </div>
</footer>

resources/views/admin/partials/mainnavbar.blade.php
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{{url('/')}}">Krishan Bari</a><button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button
    ><!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown"> 
                <a class="dropdown-item" href="#">{{ Auth::user()->name }}</a>
                <a class="dropdown-item" href="{{ url('/admin/user/changepassword') }}">Change Password</a>

                <div class="dropdown-divider"></div>
                {{-- <a class="dropdown-item" href="login.html">Logout</a> --}}
                <a class="dropdown-item" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </div>
        </li>
    </ul>
</nav>

resources/views/admin/partials/mainsidebar.blade.php
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                {{-- <div class="sb-sidenav-menu-heading">Core</div> --}}
                <a class="nav-link" href="{{url('/admin/home')}}"
                    ><div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard</a
                >
                <div class="sb-sidenav-menu-heading">Setups</div>
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts"
                    ><div class="sb-nav-link-icon"><i class="fas fa-user-cog"></i></div>
                    User Control
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div
                ></a>
                <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="{{ url('/admin/user_list') }}">Admin User List</a>
                        <a class="nav-link" href="{{ url('/admin/register') }}">Create New User</a></nav>
                </div>
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages"
                    ><div class="sb-nav-link-icon"><i class="fas fa-poll"></i></div>
                    Products Setup
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div
                ></a>
                <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth"
                            >Category
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div
                        ></a>
                        <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{{ url('/admin/category') }}">Category List</a>
                                <a class="nav-link" href="{{ url('/admin/category/create') }}">Category Add</a>
                                {{-- <a class="nav-link" href="password.html">Forgot Password</a> --}}
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError"
                            >Sub-Category
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div
                        ></a>
                        <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="{{ url('/admin/subcategory') }}">Sub-Category List</a>
                                <a class="nav-link" href="{{ url('/admin/subcategory/create') }}">Sub-Category Add</a>
                                {{-- <a class="nav-link" href="500.html">500 Page</a></nav> --}}
                        </div>
                    </nav>
                </div>
                <div class="sb-sidenav-menu-heading">Addons</div>
                <a class="nav-link" href="{{ route('product.create') }}"><div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>Add Products</a>
                <a class="nav-link" href="{{ url('/admin/product') }}"><div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>Products List</a>
                <a class="nav-link" href="{{ url('/admin/specialproduct') }}"><div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>Special Products</a>
                <a class="nav-link" href=""><div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>Products Review</a>

                <div class="sb-sidenav-menu-heading">Page Setup</div>
                <a class="nav-link" href=""><div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>Subscribers List</a>
                <a class="nav-link" href=""><div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>Slider 1 Images</a>
                <a class="nav-link" href=""><div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>Slider 2 Images</a>
                <a class="nav-link" href=""><div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>Advertise</a>
            </div>
        </div>
        <div class="sb-sidenav-footer">
            {{-- <div class="small">Logged in as:</div>
            Start Bootstrap --}}
        </div>
    </nav>
</div>